# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RtcU-VBq9ZEwxrptz66FTFDVWrE_L-b
"""

pip install gradio

import gradio as gr
from sklearn import tree
from sklearn.preprocessing import LabelEncoder

# Step 1: Prepare the dataset
# Features: [victim, money lost, data breach]
# Labels: 'cc' for Cyber Crime, 'tcc' for Through Cyber Crime
features = [
    [0, 0, 0],  # Machine, no money lost, no data breach
    [0, 0, 1],  # Machine, no money lost, data breach
    [0, 1, 1],  # Machine, money lost, data breach
    [1, 1, 1],  # Human, money lost, data breach
    [1, 1, 0],  # Human, money lost, no data breach
    [1, 0, 0],  # Human, no money lost, no data breach
    [1, 0, 1],  # Human, no money lost, data breach
    [0, 1, 0]   # Machine, money lost, no data breach
]
labels = ['cc', 'tcc', 'cc', 'cc', 'tcc', 'tcc', 'cc', 'tcc']

# Step 2: Encode the labels
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Step 3: Train the decision tree classifier
myClassifier = tree.DecisionTreeClassifier()
myModel = myClassifier.fit(features, encoded_labels)

# Step 4: Define the prediction function for Gradio interface
def predict_crime(victim, money_lost, data_breach):
    # Convert victim to binary feature
    victim_binary = 0 if victim <= 500 else 1
    # Convert inputs to the format expected by the model
    input_features = [[victim_binary, money_lost, data_breach]]
    prediction = myModel.predict(input_features)
    # Convert numerical prediction back to label
    predicted_label = label_encoder.inverse_transform(prediction)
    return predicted_label[0]

# Step 5: Create a Gradio interface
interface = gr.Interface(
    fn=predict_crime,
    inputs=[
        gr.Slider(0, 1000, step=1, label="Victim (0-500 for Machine, 500-1000 for Human)"),
        gr.Radio([0, 1], label="Money Lost (0: No, 1: Yes)"),
        gr.Radio([0, 1], label="Data Breach (0: No, 1: Yes)")
    ],
    outputs="text",
    title="Cyber Crime Classifier",
    description="Predict whether the case is 'Cyber Crime' or 'Through Cyber Crime' based on given features."
)

# Launch the Gradio interface
interface.launch()

